In [1]:
import gurobipy as gp
from gurobipy import GRB, quicksum
import pandas as pd
import copy

import numpy as np

In [2]:
df = pd.read_excel('../Naive_S_P500.xlsx', sheet_name='return')
ret = copy.deepcopy(df.drop(columns=['Unnamed: 0']))

In [3]:
ret.head()

,Date,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,...,Unnamed: 480,Unnamed: 481,Unnamed: 482,Unnamed: 483,Unnamed: 484,Unnamed: 485,Unnamed: 486,Unnamed: 487,Unnamed: 488,Unnamed: 489
0,2006-01-03,0.009078,0.003038,0.023104,0.011834,-0.001705,0.057158,0.041341,0.022843,0.007071,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006-01-04,-0.006960,0.001515,0.041710,0.028468,-0.001341,0.004926,-0.002599,0.003878,-0.011472,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-01-05,0.008430,0.012797,-0.009518,-0.007303,0.006689,0.033820,-0.009152,0.012739,-0.008692,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2006-01-06,0.004606,0.019009,0.016010,0.020726,0.029265,0.002965,0.024135,0.011399,0.023012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006-01-09,-0.016641,0.036495,-0.017206,0.040206,-0.014466,-0.015814,-0.016023,0.012903,-0.012794,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ret = ret.iloc[:5, 1:397]
n = [i for i in range(396)]

In [5]:
cov = ret.cov()
var = ret.var()
mean = ret.mean()

In [ ]:
m = gp.Model('MVS_model')
m.params.NonConvex = 2

In [ ]:
# decision varibale
w_buy = {}
w_sold = {}
l_buy = {}
l_sold = {}
s_buy = {}
s_sold = {}
u = {}
v = {}
y = {}
for i in n:
    w_buy[i] = m.addVar(lb=0.0, ub=1.0, name="w_buy-%s" % i)
    w_sold[i] = m.addVar(lb=0.0, ub=1.0, name="w_sold-%s" % i)
    l_buy[i] = m.addVar(lb=0.0, ub=1.0, name="l_buy-%s" % i)
    l_sold[i] = m.addVar(lb=0.0, ub=1.0, name="l_sold-%s" % i)
    s_buy[i] = m.addVar(lb=0.0, ub=1.0, name="s_buy-%s" % i)
    s_sold[i] = m.addVar(lb=0.0, ub=1.0, name="s_sold-%s" % i)
    u[i] = m.addVar(lb=0.0, ub=1.0, vtype=GRB.BINARY, name="u-%s" % i)
    v[i] = m.addVar(lb=0.0, ub=1.0, vtype=GRB.BINARY, name="v-%s" % i)
    y[i] = m.addVar(lb=0.0, ub=1.0, vtype=GRB.BINARY, name="y-%s" % i)
m.update()

In [9]:
# coefficient
p1 = p2 = p3 = p4 = 0.001
k = 1

In [ ]:
# objective
eq4 = quicksum(mean.iloc[i] * (w_buy[i] - w_sold[i]) for i in n)
eq5 = quicksum((w_buy[i] - w_sold[i])**2 * var.iloc[i] for i in n) + quicksum([cov.iloc[i, j] * (w_buy[i] - w_sold[i]) * (w_buy[j] - w_sold[j]) for i in n for j in n if i != j])
eq6 = quicksum(w_sold[i] for i in n)
eq7 = quicksum(p1*l_buy[i] + p2*l_sold[i] + p3*s_buy[i] + p4*s_sold[i] for i in n)

m.setObjective(eq4 - eq5 - eq6 - eq7, GRB.MAXIMIZE)

In [ ]:
eq8 = quicksum(w_buy[i] + k*w_sold[i] + p1*l_buy[i] + p2*l_sold[i] + p3*s_sold[i] + p4*s_sold[i] for i in n)
m.addConstr(eq8 == 1)
for i in n:
    m.addConstr(w_buy[i] == l_buy[i] - l_sold[i])
    m.addConstr(w_sold[i] == s_buy[i] - s_sold[i])
    m.addConstr(0.05*u[i] <= w_buy[i])
    m.addConstr(w_buy[i] <= 0.2*u[i])
    m.addConstr(0.05*v[i] <= w_sold[i])
    m.addConstr(w_sold[i] <= 0.2*v[i])
    m.addConstr(u[i] + v[i] <= y[i])
m.optimize()
for v in m.getVars():
    if(v.X > 0 and ('w' in v.varName or 'l' in v.varName or 's' in v.varName)):
        print('%s %g' % (v.varName, v.x))
print('Obj: %g' % m.objVal)